services:

  db:
    image: postgres


  redis:
    image: redis
    env_file:
      - .env

  backend_rds:
    build:
        context: .
        dockerfile: ./backend_rds/Dockerfile
    container_name: rds
    ports:
      - "8003:8003"
    depends_on:
      - db
    env_file:
      - .env

  backend_redis:
    build:
      context: .
      dockerfile: ./backend_redis/Dockerfile
    container_name: redis
    ports:
      - "8002:8002"
    depends_on:
      - redis
    env_file:
      - .env




