name: deploy backend_rds to ECR

on:
  push:
    paths:
      - 'backend_rds/**'

jobs:
  deploy-rds-to-ECR:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Connect to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: build and push
        run: |
          docker build -t backend_rds:latest -f backend_rds/Dockerfile
          docker tag backend_rds:latest ${{ env.ECR_REPOSITORY_RDS }}:latest
          docker push ${{ env.ECR_REPOSITORY_RDS }}:latest


env:
  APP_INSTANCE_IP: 3.71.186.235
